### ISSUE TITLE
New Theme function is not working as intended

### ISSUE THREAD

**Issue by Voinpahoin** [khanhas/Spicetify#51] opened 2018-07-25 18:34 UTC
Just installed for the first time, i got the default theme working just fine but when I try to create a new theme and change the colours, it won't let me change them. Clicking the colors does nothing and the same problem happens with buttons like Edit CSS. What could cause this?

**Comment by khanhas** [comment] 2018-07-26 06:27
Oh you right, New Theme function is not work as intended.
Try to use Duplicate Current Theme on Spicetify Default Theme and make changes with it.
There're change theme buttons on top
I will try to find cause later

**Comment by khanhas** [comment] 2018-07-29 05:41
Fixed in 1.7.4

**Closed as completed by khanhas** 2018-07-29 05:41 UTC
